### ISSUE TITLE
0.2.5 make zsh-navigation-tools unusable / non-exit-able

### ISSUE THREAD

**Issue by ronjouch** [tarruda/zsh-autosuggestions#116] opened 2016-02-15 01:51 UTC
(May be related to https://github.com/tarruda/zsh-autosuggestions/issues/115 , appeared at the same time)

---

Minimal `.zshrc`:

```bash
ZSH=$HOME/.oh-my-zsh
plugins=(zsh-navigation-tools zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh
```

Scenario:

* Press Ctrl+R to open [zsh-navigation-tools](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/zsh-navigation-tools).
* Press ENTER to select the first entry

**Expected**: first entry is sent to current line

**Actual**: nothing happens: screen flickers and zsh-navigation-tools become impossible to exit (Ctrl+C, Ctrl+D don't help)

**Comment by george-b** [comment] 2016-02-15 13:25
I'm seeing a similar thing when using fzf.

Can be re-produced with the following .

```zsh
source $HOME/.zsh/plugins/autosuggestions/zsh-autosuggestions.zsh

fzf-history-widget() {
  LBUFFER=$(fc -l 1 | fzf +s --tac -n2..,.. | sed "s/ *[0-9*]* *//")
  zle redisplay
}
zle -N fzf-history-widget
bindkey -e '^r' fzf-history-widget
```
@ronjouch do you see this issue if you comment out the references to `zle redisplay`? It seems to prevent this for me, however the redisplay is most certainly needed. I guess something in autosuggestions may have changed how this is handled.

I will try to step through the commits in more detail when I have some time.

**Comment by ronjouch** [comment] 2016-02-15 14:26
@george-b yeah, v0.2.5 is this single commit :)

Regarding your request for info, I'm a zsh user but my knowledge of programming zsh is very, very limited and I have no idea what you're talking about. Can you precise what you mean by *"comment out the references to `zle redisplay`"*? I have no such thing in my zshrc.

**Comment by george-b** [comment] 2016-02-15 14:48
> Regarding your request for info, I'm a zsh user but my knowledge of programming zsh is very, very limited and I have no idea what you're talking about. Can you precise what you mean by "comment out the references to zle redisplay"? I have no such thing in my zshrc.

Within [zsh-navigation-tools](https://github.com/robbyrussell/oh-my-zsh/tree/40016afdc4c4ecdab6092e4f8c5c8648e27e5524/plugins/zsh-navigation-tools) there will be invocations of `zle redisplay`, [e.g.](https://github.com/robbyrussell/oh-my-zsh/search?utf8=%E2%9C%93&q=zle+redisplay)

You can comment these out by prefixing them with a `#`. These are of course needed, in my case without the redisplay output is displayed before my prompt. However with the redisplay I am simply dropped back into fzf in my case since updating to v0.2.5 of autosuggestions.

I'm sure @ericfreese has far better knowledge of zsh widget than I, hopefully this cause of this is straight forward if you find the same behavior as I do.

**Comment by ericfreese** [comment] 2016-02-15 14:56
So what 0.2.5 did is bind widgets not found in the [CLEAR, ACCEPT, or PARTIAL_ACCEPT lists](https://github.com/tarruda/zsh-autosuggestions/blob/master/src/config.zsh#L15-L40) to the `_zsh_autosuggest_modify` function: https://github.com/tarruda/zsh-autosuggestions/commit/5e419da3267c606eab1cfc76334cc953e903c718#diff-2a58eb2e47d1b3ee3c072d264886fc66R52

Before 0.2.5, the `redisplay` widget was not bound, but now it is. I believe this is the same issue as described [here](https://github.com/tarruda/zsh-autosuggestions/issues/107#issuecomment-183824034), and I believe the correct fix is for zsh-navigation-tools to use `zle .redisplay` or `zle .redisplay -w`.

However, it's not really feasible to expect all of these other plugins to fix how they're calling zle, so I'll try to spend some time today looking into how we can handle those cases in this codebase.

**Comment by george-b** [comment] 2016-02-15 15:07
> I believe the correct fix is for zsh-navigation-tools to use zle .redisplay or zle .redisplay -w.

Thanks! I can confirm this works for me. If you don't mind me asking what does the `.` prefix do? I've had a skim through `zshzle` man page but am still left wondering.

**Comment by ericfreese** [comment] 2016-02-15 15:09
No probem, glad it helps.

From http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Zle-Widgets:

> Each built-in widget has two names: its normal canonical name, and the same name preceded by a ‘.’. The ‘.’ name is special: it can’t be rebound to a different widget. This makes the widget available even when its usual name has been redefined.

**Comment by ericfreese** [comment] 2016-02-15 15:34
Ok, I've just pushed v0.2.6, which I believe will fix these issues by no longer referring to the $WIDGET variable. Please give that a shot.

**Closed** 2016-02-15 15:35 UTC

**Comment by george-b** [comment] 2016-02-15 15:38
> Ok, I've just pushed v0.2.6, which I believe will fix these issues by no longer referring to the $WIDGET variable. Please give that a shot.

It does fix this issue however it has broken tab completion. Let me know if you want me to create a new issue for this.

```zsh
$ cd _main_complete:199: command not found: expand-or-complete
_main_complete:199: command not found: modify
_main_complete:199: command not found: expand-or-complete
_main_complete:199: command not found: modify
```

**Comment by ericfreese** [comment] 2016-02-15 15:41
Shoot. Yeah, let's make a separate issue for that.

**Comment by ericfreese** [comment] 2016-02-15 15:45
Ah, forgot a pesky backslash. Will push v0.2.7 to fix that momentarily.
