### ISSUE TITLE
iTerm2 crashes

### ISSUE THREAD

**Issue by thenitai** [tarruda/zsh-autosuggestions#107] opened 2016-02-07 22:38 UTC
(As requested in #103 I created this as a separate topic)

While the initial error is now resolved the plugin now crashes my terminal window as soon as I enter a "space" after any command, i.e. "ping(space)".

I'm using iTerm2 and load all plugins with the zgen framework. Here is my setup:

In a .zgen file
```
source ~/.zsh/zsh-autosuggestions/dist/autosuggestions.zsh
zgen load zsh-users/zsh-syntax-highlighting
```
In .zshrc
```
ZSH_AUTOSUGGEST_CLEAR_WIDGETS=("${(@)ZSH_AUTOSUGGEST_CLEAR_WIDGETS:#(up|down)-line-or-history}")

ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(history-substring-search-up history-substring-search-down)

autosuggest_start
```

Your plugin is loaded from the repro and is on the v0.1.0 branch.

**Comment by kergoth** [comment] 2016-02-11 19:18
I'm seeing a similar behavior, except that it's not a crash, and it's when I hit tab, not space. In my case, the iterm2 window closes because the process exited, because zsh segfaulted. Haven't had time to investigate further, my gdb-fu is weak.

**Comment by andrewsuzuki** [comment] 2016-02-14 00:45
@kergoth Same problem here, I'm using the latest iTerm2 nightly and pressing tab immediately closes the window.

**Comment by ericfreese** [comment] 2016-02-14 04:19
Can you confirm you still have this problem with a minimal configuration?

Try installing with:

```shell
$ git clone git://github.com/tarruda/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
```

and confirming you have the latest version:

```shell
$ git -C ~/.zsh/zsh-autosuggestions rev-parse --short HEAD
0ae5907
```

and using the following `.zshrc`:

```shell
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
```

Then start a new terminal session and confirm the problem persists.

**Comment by kergoth** [comment] 2016-02-14 04:50
zsh does not crash in that case, here. I'll try to isolate the configuration which crashes.

**Comment by ericfreese** [comment] 2016-02-14 04:53
> I'll try to isolate the configuration which crashes.

Thanks! In my experience this is usually caused by invoking a `zle` widget that is in one of [these lists](https://github.com/tarruda/zsh-autosuggestions/blob/master/src/config.zsh#L15-L61). This causes an infinite recursion and segfault. So, when isolating, it might help to look for lines that call `zle`.

**Comment by lexinator** [comment] 2016-02-14 04:53
I've been trying to narrow it down to specific so far zsh-syntax-highlighting and zsh-history-substring-search cause the same coredump. zsh v5.0.8 and v5.2.  Order does matter.  if I do zsh-syntax-highlighting first and then zsh-autosuggestions.zsh it does behave the same.  set -x has not revealed anything obvious either.

```
% /bin/zsh --version
zsh 5.0.8 (x86_64-apple-darwin15.0)
% /bin/zsh -f
% cd ~/src/zsh-autosuggestions
% % git rev-parse --short HEAD
011f542
% . zsh-autosuggestions.zsh
% cd ~/src/zsh-syntax-highlighting
% git remote -v | tail -1
origin	git://github.com/zsh-users/zsh-syntax-highlighting.git (push)
% git rev-parse --short HEAD
683f483
% . zsh-syntax-highlighting.zsh
% <any character>
% zsh: segmentation fault  /bin/zsh -f
```

**Comment by ericfreese** [comment] 2016-02-14 04:55
>and it's when I hit tab

@kergoth This is another clue. What is tab bound to? Run `bindkey '^I'` to find out

**Comment by ericfreese** [comment] 2016-02-14 04:58
Thanks @lexinator I'll look into this.

**Comment by lexinator** [comment] 2016-02-14 05:06
both zsh-syntax-highlighting and zsh-history-substring-search define zle, and the coredump is 500ish deep stacktrace, so I suspect your theory on recursive zle is correct.  thanks.

**Comment by kergoth** [comment] 2016-02-14 05:07
Indeed, thanks for the guidance, you're absolutely correct. Is the correct fix to add the zle widgets in question that call the originals to ZSH_AUTOSUGGEST_MODIFY_WIDGETS?

**Comment by ericfreese** [comment] 2016-02-14 05:17
@lexinator I believe the segfault you produced [above](https://github.com/tarruda/zsh-autosuggestions/issues/107#issuecomment-183821446) is created by loading zsh-syntax-highlighting after [`_zsh_autosuggest_start`](https://github.com/tarruda/zsh-autosuggestions/blob/master/src/start.zsh#L7) has been called and the widgets have been bound. This is delayed by the plugin using `add-zsh-hook` to run a function before each new prompt. Because you're sourcing syntax-highlighting at a different prompt (after sourcing zsh-autosuggestions), that hook has already run and the widgets have been bound.

Sourcing both plugins at the same prompt (simulating the behavior of loading `.zshrc`) avoids the problem:

```shell
% /bin/zsh -f
% . ~/src/zsh-autosuggestions/zsh-autosuggestions.zsh; . ~/src/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```

**Comment by ericfreese** [comment] 2016-02-14 05:33
@kergoth 

> Is the correct fix to add the zle widgets in question that call the originals to ZSH_AUTOSUGGEST_MODIFY_WIDGETS?

My personal belief is that the correct fix is for any plugin invoking a widget that it does not have control over to do one of two things:

1. Use the builtin dot-prefixed version of the widget instead if the plugin only wants the default behavior to occur (i.e. use `zle .self-insert` instead of `zle self-insert` in case the `self-insert` widget has been overridden by someone).
2. Call `zle` with the `-w` flag to set `$WIDGET` and other associated variables correctly when the widget is invoked if the plugin doesn't particularly care what happens when the widget is invoked.

Though it seems there's a lot of code out there that does neither of these things and just calls possibly user-defined widgets without the `-w` flag set. `zsh-history-substring-search` does it [here](https://github.com/zsh-users/zsh-history-substring-search/blob/e2ab5b8214c50c2cb39d370fe4863576fd3eeffe/zsh-history-substring-search.zsh#L300), `bracketed-paste-magic` does it [here](https://github.com/zsh-users/zsh/blob/aba7c00698fdd459d2f17f84ed371413458afae5/Functions/Zle/bracketed-paste-magic#L178) and [here](https://github.com/zsh-users/zsh/blob/aba7c00698fdd459d2f17f84ed371413458afae5/Functions/Zle/bracketed-paste-magic#L187), and I'm sure that's just the beginning. So this makes me wonder if I'm wrong in my assumption and that I should be handling things differently in this plugin. Especially since I'm relatively new to all of this.

So for now, yeah, you can sometimes break the infinite recursion by removing the widget in question from one of the config lists (this is what [the fix in the readme for `zsh-history-substring-search`](https://github.com/tarruda/zsh-autosuggestions#zsh-history-substring-search) is all about), but it might not be the best workaround for every case (fixing the problems caused by `bracketed-paste-magic` required [setting a separate zstyle](https://github.com/tarruda/zsh-autosuggestions/issues/102#issuecomment-183770990)). So I think we'll have to come up with workarounds on a case-by-case basis until I can confirm my belief above and we can get PRs merged into all the plugins causing these issues.

**Comment by lexinator** [comment] 2016-02-14 06:25
sorry to have crashed this issue since mine seems now unrelated.

@ericfreese sourcing the scripts in a single run fixed the coredump.  The next issue I ran into was https://github.com/solarnz/dotfiles/blob/master/zsh/10-expand-or-complete-with-dots.zsh causing another coredump.  As you said in https://github.com/tarruda/zsh-autosuggestions/issues/107#issuecomment-183824034, the fix it to prefix '.' on the other two zle functions to avoid recursion.

thanks for the quick reply.

**Comment by ericfreese** [comment] 2016-02-15 15:37
I believe v0.2.6 should fix all of these issues without requiring changes to other plugins. Please give that a shot.

**Closed by ericfreese** 2016-02-15 15:37 UTC

**Comment by shangsunset** [comment] 2016-04-21 04:56
just installed the plugin, crashes still happen upon pressing forward char. I installed as oh-my-zsh plugin
```
plugins=(git z nvm zsh-syntax-highlighting zsh-autosuggestions)
```

**Comment by MikeBailleul** [comment] 2017-03-13 05:01
I have the same problem.
II have the following in my ~/.zshrc
...
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
...

Every time I do source ~/.zshrc, the next key press make iterm crash.

If I comment one of the above lines, the problem is gone.

**Comment by kylealwyn** [comment] 2017-03-14 16:57
Same issue with iTerm2. Removing zsh-autosuggestions from plugins resolves issue.


```
plugins=(git zsh-syntax-highlighting zsh-autosuggestions)
```

**Comment by ericfreese** [comment] 2017-03-20 22:59
Please try the `develop` branch. What you were likely seeing was issue #166, which has been fixed on the `develop` branch but not yet on `master`.

**Comment by MikeBailleul** [comment] 2017-03-20 23:12
Awesome, thanks.
