### ISSUE TITLE
Tabbing produces strange behavior

### ISSUE THREAD

**Issue by alexbw** [tarruda/zsh-autosuggestions#14] opened 2014-01-04 16:19 UTC
When I hit <Tab> when autosuggestions is enabled, it deletes the previous line, and scrolls up the terminal. I'm using

https://github.com/skwp/dotfiles

When autosuggestions is disabled, this phenomena does not occur.

**Comment by bachue** [comment] 2015-03-04 06:53
+1

**Comment by mefiblogger** [comment] 2015-04-09 19:21
+1

Same here with oh-my-zsh, steeef theme and plugins: brew, composer, fasd, git, jira, npm, sudo and wd.

**Comment by faceleg** [comment] 2015-04-10 03:48
Yes this plugin needs serious attention from someone with time and energy. This could be you!

**Comment by faceleg** [comment] 2015-05-21 23:33
Has this been addressed for you by the recent update?

**Comment by Alessandro-Barbieri** [comment] 2015-05-22 17:01
I can confirm that tabbing removes the previous line.

**Comment by twe4ked** [comment] 2015-05-22 17:16
I can also confirm the problem still exists with the most recent version. Thanks for all the work you guys (@faceleg, @jirutka, et al.) have been doing lately. I'd love for this plugin to work consistently.

**Comment by jirutka** [comment] 2015-05-22 17:18
@twe4ked Could you please provide us your .zshrc file, information about used terminal, ZSH version and operating system?

**Comment by twe4ked** [comment] 2015-05-22 17:24
Sure:

- `zsh 5.0.2 (x86_64-apple-darwin13.0)`
- OS X 1.9.5
- iTerm 2 (recent nightly), the problem also exists in Terminal.app

Here is a "compiled" version of my `.zshrc`: https://gist.github.com/twe4ked/00cb0e5bfaa98e9cfac4

**Comment by twe4ked** [comment] 2015-05-22 17:30
Sorry, I'm an idiot. It was the completion waiting dots thing as mentioned in the README. I'm using a different version that doesn't have that environment variable so when I checked it I didn't notice it.

**Comment by jirutka** [comment] 2015-05-22 17:34
@twe4ked No problem, I’m glad that it works for you now. :smiley_cat:

@Alessandro-Barbieri Could you please ensure that you’re not using “completion waiting dots” feature?

**Comment by Alessandro-Barbieri** [comment] 2015-05-22 17:37
I put
```export COMPLETION_WAITING_DOTS=false```
in .zshrc
but the problem still remain.

**Comment by twe4ked** [comment] 2015-05-22 17:43
@Alessandro-Barbieri what output to you get if you run `bindkey "^I"`?

**Comment by Alessandro-Barbieri** [comment] 2015-05-22 17:45
Got ```"^I" expand-or-complete-with-indicator```

**Comment by twe4ked** [comment] 2015-05-22 17:45
That looks like it's the problem. Search you zshrc for where that's being set.

**Comment by Alessandro-Barbieri** [comment] 2015-05-22 17:56
Found: is in prezto
https://github.com/sorin-ionescu/prezto/blob/master/modules/editor/init.zsh
I removed it and it no more delete lines.

**Comment by jirutka** [comment] 2015-05-22 17:59
Great! I’ll update readme with troubleshooting and more information about this problem, and then we can close this issue.

**Closed** 2015-05-23 00:41 UTC
