### ISSUE TITLE
bindkey "^I" is not overrided

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [tarruda/zsh-autosuggestions#64] opened 2015-05-24 12:30 UTC
We know from #14 that "^I" should not be bind to zprezto expand-or-complete-with-indicator.
From https://github.com/sorin-ionescu/prezto/issues/884
An override can be added in order to avoid commenting these lines?
https://github.com/sorin-ionescu/prezto/blob/a84ac5b0023d71c98bb28a68c550dc13f6c51945/modules/editor/init.zsh#L303-L304

**Comment by faceleg** [comment] 2015-06-07 23:45
Would you PR?

**Comment by Alessandro-Barbieri** [comment] 2015-06-08 00:27
PR is pull request?

I try to explain better the issue:
if I put 
```bindkey -r "^I"```
inside .zshrc (or at the last line)
it complains that ```bindkey: no such keymap `'```

if I type in in the terminal, it works

**Comment by sorin-ionescu** [comment] 2015-11-15 04:15
I can add this override in Prezto when I add zsh-autosuggestions as an external module unless you think it's better for zsh-autosuggestions to handle it since there are others who may have completion indicators.

**Comment by ericfreese** [comment] 2016-01-27 14:57
There's a rewrite underway in PR #91. It's available on branch `v0.1.x`. Please try using that branch, and let me know if it solves your problem.

**Comment by Alessandro-Barbieri** [comment] 2016-01-27 16:03
Seems fixed in branch v0.1.x

**Comment by Alessandro-Barbieri** [comment] 2016-01-27 16:10
[**@Alessandro-Barbieri**](https://github.com/Alessandro-Barbieri) commented on [27 gen 2016, 17:03 CET](https://github.com/tarruda/zsh-autosuggestions/issues/64#issuecomment-175710316 "2016-01-27T16:03:27Z - Replied by Github Comment Enhancer"):
> Seems fixed in branch v0.1.x

**Comment by Alessandro-Barbieri** [comment] 2016-01-27 16:11
I still have the same prioblem

**Comment by ericfreese** [comment] 2016-01-28 23:02
Thanks for checking.

I'm having some trouble understanding exactly what the issue is here (I'm not very familiar with zprezto), and only started using this plugin myself a few weeks ago.

What exactly are you trying to accomplish? What problem are you running in to? How can I reproduce it?

Thanks

**Comment by Alessandro-Barbieri** [comment] 2016-01-29 00:42
> What exactly are you trying to accomplish?

To run zprezto and zsh autosuggestions at the same time

>What problem are you running in to?

Tab removes the previous line

>How can I reproduce it?

Just install zprezo and zsh-autosuggestion (I think is enough)

**Comment by ericfreese** [comment] 2016-01-29 01:07
> Just install zprezo and zsh-autosuggestions (I think is enough)

I will try this tomorrow and see if I can reproduce.

In the mean time, I just pushed a fix to autocomplete (#73) that may solve the problem. You might update again and see if the problem is solved by that.

**Comment by ericfreese** [comment] 2016-02-14 07:08
I believe this is a bug in zprezto. [These lines](https://github.com/sorin-ionescu/prezto/blob/f2a826e963f06a204dc0e09c05fc3e5419799f52/modules/editor/init.zsh#L190-L191) should use the builtin dot-prefixed version of those widgets or use the `-w` flag to set  `$WIDGET` and related variables correctly. See the discussion on this [here](https://github.com/tarruda/zsh-autosuggestions/issues/107#issuecomment-183824034). I believe the right fix in this case is to use the dot-prefixed versions of those widgets.

cc @sorin-ionescu Thoughts?

**Comment by ericfreese** [comment] 2016-02-15 15:38
I believe v0.2.6 should fix all of these issues without requiring changes to other plugins. Please give that a shot @Alessandro-Barbieri

**Closed** 2016-02-15 15:48 UTC
Labels: bug, plugin-compatibility

**Comment by Alessandro-Barbieri** [comment] 2016-02-15 16:13
I still have [this](https://github.com/tarruda/zsh-autosuggestions/issues/14) problem.

**Comment by ericfreese** [comment] 2016-02-16 00:24
> I still have this problem.

Can you confirm that *this* problem, reported in *this* issue (#64), is now fixed?

Are you now saying you're having a separate issue? If so, can you please create a new issue with a minimal .zshrc and **clear** steps to reproduce the problem? The code has changed so much since the issue you linked was created, I doubt much of that discussion is still relevant.

**Comment by Alessandro-Barbieri** [comment] 2016-02-16 17:45
Nevermind, I was still using the old method to run zsh-autosuggestions. #14 and #64 are fixed for me.
